### ISSUE TITLE
No guide of how to use the gui/cli

### ISSUE THREAD

**Issue by yassinshehata-git** [GrbavaCigla/opendragui#1]
New linux users or even experienced linux users would have trouble as they dont know how to use gui/cli instead of the manual option since they dont know how the code work

**Comment by GrbavaCigla** [comment]
Yeah, sorry, I never finished opendragonutils. I planned porting this driver to [libratbag](https://github.com/libratbag/libratbag), but never got the time. Try user space drivers from [dokutan](https://github.com/dokutan) or use manual documentation from [openredragon](https://github.com/GrbavaCigla/opendragon). If you have any specific questions don't hesitate to ask.
